@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Apr 24 18:42:08 +0530 2026
REM SW Build 6299465 on Fri Nov 14 19:35:11 GMT 2025
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
set SIM_VER_XSIM=
set GCC_VER_XSIM=9.3.0
REM simulate design
echo "xsim mehak_testbench_behav -key {Behavioral:sim_1:Functional:mehak_testbench} -tclbatch mehak_testbench.tcl -view C:/Users/mehak/project_1/mehak_testbench_behav.wcfg -log simulate.log"
call xsim  mehak_testbench_behav -key {Behavioral:sim_1:Functional:mehak_testbench} -tclbatch mehak_testbench.tcl -view C:/Users/mehak/project_1/mehak_testbench_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
